violation_responses = {
    # A. Uniform and Appearance Violations
    "failure to wear the prescribed school uniform": "This is a Uniform and Appearance Violation. Please report or clarify with the SAO to resolve the matter.",
    "incomplete or improper uniform": "This counts as a Uniform and Appearance Violation. The SAO can provide the correct dress code details. Please report to them.",
    "wearing civilian clothes": "This is not allowed unless authorised and is a Uniform and Appearance Violation. Please report to the SAO for further instructions.",
    "inappropriate attire": "This falls under Uniform and Appearance Violations. Please check and report to the SAO.",
    "crop tops": "Crop tops are inappropriate per school policy. This is a Uniform Violation. Report to the SAO for proper guidance.",
    "ripped jeans": "Ripped jeans violate the dress code and fall under Uniform Violations. Please report this to the SAO.",
    "short skirts": "Short skirts are part of Uniform Violations. Please report to the SAO for clarification.",
    "shorts": "Wearing shorts instead of the required uniform is a Uniform and Appearance Violation. Kindly inform the SAO.",
    "sleeveless tops": "These are not permitted and are a Uniform and Appearance Violation. Report this to the SAO.",
    "slippers": "Unless medically exempted, wearing slippers is a Uniform Violation. Please report the case to the SAO.",
    "sandals": "Wearing sandals without authorisation is a Uniform Violation. Kindly report this to SAO.",
    "wearing hoodie": "This may be considered a Uniform Violation depending on policy. Please consult the SAO.",
    "colored hair": "Unnatural hair colours may violate grooming rules. This is a Uniform Violation. Please report this to SAO for guidance.",

    # B. ID and Access Violations
    "not wearing id": "Failing to wear your ID visibly is an ID and Access Violation. Please report this to the SAO.",
    "not presenting id": "Refusing to show your ID when requested is an ID Violation. Report to SAO to address this.",
    "lending id": "Sharing your ID is a serious ID Violation. This must be reported to SAO for documentation.",
    "fake id": "Possessing or using a fake ID is a serious ID Violation. Please report this immediately to SAO.",
    "tampered id": "Tampering with a school ID is an ID Violation. Kindly report this to the SAO.",
    "restricted areas": "Being in restricted areas without permission is an Access Violation. Please inform the SAO.",
    "id not visible": "Not displaying your ID is a minor ID Violation. Please report to the SAO for recordkeeping.",
    "lost id": "A lost ID should be reported to the SAO immediately for replacement processing.",
    "someone using my id": "Using another student's ID is identity misuse. This is a Violation—please report to SAO.",

    # C. Behavioral Violations
    "loitering": "Loitering during class hours is a Behavioral Violation. Report this to the SAO for intervention.",
    "disrupting class": "Disruption of class is a Behavioral Violation. Kindly report this to the SAO.",
    "disrespecting faculty": "Disrespecting faculty or staff is a Behavioral Violation. Please report this to the SAO.",
    "offensive language": "Using offensive language is a Behavioral Violation. Report this to SAO.",
    "bullying": "Bullying is a major Behavioral Violation. Please report it to SAO or the guidance office.",
    "harassment": "Harassment is not tolerated. This is a Behavioral Violation. Kindly report this to SAO.",
    "intimidation": "Intimidation is a Behavioral Violation. Please report this to the SAO immediately.",
    "fighting": "Fighting is unacceptable and is a Behavioral Violation. Report this to SAO right away.",
    "physical altercation": "Engaging in physical altercations is a Behavioral Violation. Please report this to the SAO.",
    "insubordination": "Not following staff instructions is insubordination—a Behavioral Violation. Report to the SAO.",
    "making threats": "Threatening others is a serious Behavioral Violation. This must be reported to SAO.",
    "yelling at teacher": "Raising your voice at staff is a Behavioral Violation. Report this to SAO.",
    "someone called me stupid": "That is verbal bullying and a Behavioral Violation. Please report this to the SAO.",
    "mocking students": "Mockery is a form of bullying and a Behavioral Violation. Kindly report this to SAO.",
    "pushing a classmate": "Pushing others is a Behavioral Violation. Please report this to SAO immediately.",
    "spitting on someone": "Spitting on someone is harassment and a Behavioral Violation. Report to SAO right away.",
    "arguing loudly in class": "This is disruptive and a Behavioral Violation. Report to SAO for further handling.",
    "threatening a teacher": "Threats toward school staff are serious Behavioral Violations. Please report to SAO.",
    "kicking a classmate": "Kicking others is violent behavior and a Behavioral Violation. Report to SAO immediately.",
    "laughing at someone": "Public humiliation is bullying. This is a Behavioral Violation. Please report to SAO.",
    "being embarrassed publicly": "Public humiliation can be bullying. Kindly report this Behavioral Violation to SAO.",
    "spreading false rumors": "Spreading rumors is a form of bullying and a Behavioral Violation. Report to SAO.",
    "shouting in hallway": "Creating noise in hallways is a Behavioral Violation. Report to SAO if recurring.",

    # D. Academic Violations
    "cheating": "Cheating is an Academic Violation. Please report this to the SAO or instructor.",
    "plagiarism": "Plagiarism is a serious Academic Violation. Kindly report this to the academic department or SAO.",
    "forgery": "Forgery is academic misconduct. Please report to the SAO immediately.",
    "tampering records": "Tampering with academic records is a Violation. This should be reported to SAO.",
    "copying answers": "Copying during assessments is academic dishonesty. Please report this to SAO.",
    "using cheat sheet": "Possession of cheat materials is an Academic Violation. Report to the SAO.",
    "hiring someone to do my work": "Outsourcing assignments is contract cheating and a serious Academic Violation. Report to SAO.",

    # E. Campus Conduct Violations
    "vaping": "Vaping on campus is prohibited and a Conduct Violation. Please report to SAO.",
    "smoking": "Smoking is a Campus Conduct Violation. Kindly report this to SAO.",
    "alcohol": "Alcohol on campus is a serious Violation. Please report this to the SAO immediately.",
    "illegal drugs": "Drug use or possession is a critical Conduct Violation. This must be reported to SAO.",
    "weapons": "Weapons on campus are a major safety concern. Report to SAO or security immediately.",
    "gambling": "Gambling on school grounds is a Conduct Violation. Please report to SAO.",
    "unauthorized selling": "Selling without permission is a Campus Violation. Kindly report this to SAO.",
    "found student drinking": "Alcohol use on campus is not permitted. Report this to SAO.",
    "someone vaping in restroom": "Vaping anywhere on campus is a Violation. Report this incident to SAO.",
    "selling snacks in class": "Selling goods without approval is a Campus Conduct Violation. Report to SAO.",

    # F. Property and Facility Violations
    "vandalism": "Vandalism is a Property Violation. Please report this to SAO immediately.",
    "theft": "Theft is a serious Property Violation. Report to SAO or school authorities at once.",
    "littering": "Littering violates campus cleanliness standards. Report repeated offenses to SAO.",
    "waste disposal": "Improper waste disposal is a Property Violation. Please inform SAO.",
    "lab equipment misuse": "Misuse of equipment is a Property and Facility Violation. Report to lab supervisor or SAO.",
    "tampering fire alarm": "Tampering with fire alarms is a serious safety violation. Report this to SAO immediately.",
    "tampering extinguisher": "Misusing extinguishers is a Facility Violation. Contact SAO immediately.",
    "spraying graffiti": "Graffiti is a form of vandalism. Please report this to the SAO or facilities.",
    "damaged classroom chairs": "Damaging chairs is a Property Violation. Report this incident to SAO.",
    "broken window": "A broken window is a Facility Violation. Please notify SAO.",
    "stealing phone": "Phone theft is a Property Violation. Report to SAO or security.",
    "writing on desks": "Defacing desks is a form of vandalism. Please report this to SAO.",
    "flushing garbage in toilet": "This may damage school plumbing. It is a Facility Violation. Report to SAO.",
    "removing posters": "Removing official posters is a Property Violation. Please notify SAO."
}